/***
 The function loadHeader() is used to load the header component into the page from the navbar.html file.
 */
function loadHeader() {
    fetch('/src/navbar.html')
        .then(response => response.text())
        .then(data => {
            document.getElementById('header').innerHTML = data;
        })
        .catch(error => console.error('Error loading the content of navbar', error));
}

/***
 The function loadFooter() is used to load the footer component into the page from the footer.html file.
 */
function loadFooter() {
    fetch('/src/footer.html')
        .then(response => response.text())
        .then(data => {
            document.getElementById('footer').innerHTML = data;
        })
        .catch(error => console.error('Error loading the content of footer', error));
}

/***
 The function loadContent(page) is used to load the main component into the page from the dedicated .html file.
 @param page - the location where the main component html resides
 */
function loadContent(page) {
    fetch(page)
        .then(response => response.text())
        .then(data => {
            document.getElementById('content').innerHTML = data;
        })
        .catch(error => console.error('Error loading the content of ' + page, error));
}

/***
 Adding a DOMContentLoaded event listener to the document to ensure the subsequent function calls are called after
 the static html components are loaded. It also exposes the sendForm() and loadContent() functions globally.
 */
document.addEventListener('DOMContentLoaded', () => {
    loadHeader();
    loadFooter();
    loadContent('/src/home.html');

    window.sendForm = sendForm;
    window.loadContent = loadContent;

})

/***
 The function sendForm() is used to send a form using the emailjs API. It validates the input fields of the form,
 then sends the form's content to the emailjs API using *my* public key, service id, and template id.
 Replace the public key, service id, and template id values with your own values which can be generated by visiting
 and registering to https://www.emailjs.com/
 */
function sendForm() {
    const name = document.getElementById('name').value;
    const email = document.getElementById('email').value;
    const message = document.getElementById('message').value;

    if (name === '') {
        alert("Please enter your name");
    }
    else if(email === '' || !email.includes("@") || !email.includes(".")) {
        alert("Please enter a valid email");
    }
    else if(message === '') {
        alert("Please enter your message");
    }
    else{
        event.preventDefault()
        emailjs.init('I6XAeZBxH6tn7Dqg3')

        const serviceID = 'service_dvofvzg';
        const templateID = 'template_1qbyhbf';

        emailjs.sendForm(serviceID, templateID, "#contact_form")
            .then(() => {
                alert('Sent!');
            }, (err) => {
                alert(JSON.stringify(err));
            });
    }
}