name: Update Repos Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install node-fetch

      - name: List directory contents before running script
        run: |
          mkdir -p res/files  # Ensure the directory exists
          ls -la res/files

      - name: Run script to update repos data
        run: node js/jsonUpdater.mjs

      - name: Show updated file content
        run: |
          echo "Showing the content of res/files/repos_data.json:"
          cat res/files/repos_data.json

      - name: List directory contents after running script
        run: ls -la res/files

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          
          if [ -f res/files/repos_data.json ]; then
            git add -f res/files/repos_data.json
          fi
          
          git status

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'Update repos data'
            git push origin HEAD:main
          fi